import streamlit as st
import pandas as pd
import numpy as np
import joblib
import plotly.express as px
import plotly.graph_objects as go
from datetime import datetime
import warnings
warnings.filterwarnings('ignore')

# Set page configuration
st.set_page_config(
    page_title="Customer Data Platform",
    page_icon="📊",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom CSS for better styling
st.markdown("""
    <style>
    .main {
        padding: 0rem 1rem;
    }
    .stTabs [data-baseweb="tab-list"] {
        gap: 24px;
    }
    .stTabs [data-baseweb="tab"] {
        height: 50px;
        padding-left: 20px;
        padding-right: 20px;
    }
    </style>
    """, unsafe_allow_html=True)

# Load models and scalers
@st.cache_resource
def load_models():
    """Load all saved models and scalers"""
    try:
        churn_model = joblib.load('/Users/apple/Desktop/MARKETING PROJ/best_churn_model.pkl')
        churn_scaler = joblib.load('/Users/apple/Desktop/MARKETING PROJ/scaler_churn.pkl')
        gg_model = joblib.load('/Users/apple/Desktop/MARKETING PROJ/gamma_gamma_model.pkl')
        feature_names = joblib.load('/Users/apple/Desktop/MARKETING PROJ/feature_names.pkl')
        
        return churn_model, churn_scaler, gg_model, feature_names
    except Exception as e:
        st.error(f"Error loading models: {e}")
        st.stop()

# Load customer data for analysis
@st.cache_data
def load_customer_data():
    """Load customer-level data for EDA tab"""
    try:
        df = pd.read_csv('/Users/apple/Desktop/MARKETING PROJ/cleaned_customer_transactions.csv')
        return df
    except Exception as e:
        st.error(f"Error loading customer data: {e}")
        return None

def cld():
    """Load customer-level data for EDA tab"""
    try:
        df = pd.read_csv('/Users/apple/Desktop/MARKETING PROJ/customer_level_data.csv')
        return df
    except Exception as e:
        st.error(f"Error loading customer data: {e}")
        return None


# Initialize models
churn_model, churn_scaler, gg_model, feature_names = load_models()

# App Title
st.title("🎯 Customer Data Platform Dashboard")
st.markdown("### Predict Customer Churn & Lifetime Value")
st.markdown("---")

# Create tabs
tab1, tab2, tab3 = st.tabs(["🔮 Predictions", "📊 Data Analysis", "ℹ️ About"])

# ============================
# TAB 1: PREDICTIONS
# ============================
with tab1:
    st.header("Customer Predictions")
    
    col1, col2 = st.columns(2)
    
    with col1:
        st.subheader("📉 Churn Prediction")
        st.markdown("Predict if a customer will churn based on their behavior")
    
    with col2:
        st.subheader("💰 CLV Prediction")
        st.markdown("Estimate Customer Lifetime Value using Gamma-Gamma model")
    
    st.markdown("---")
    
    # Create two columns for input
    input_col1, input_col2 = st.columns(2)
    
    with input_col1:
        st.markdown("#### 📋 Customer Purchase Behavior")
        
        total_invoices = st.number_input(
            "Total Number of Invoices (type a number from 1 - 1000)",
            min_value=1,
            max_value=1000,
            value=10,
            help="Total number of invoices this customer has"
        )
        
        total_revenue = st.number_input(
            "Total Revenue (Rs. )",
            min_value=0.0,
            max_value=1000000.0,
            value=500.0,
            step=10.0,
            help="Total revenue generated by this customer"
        )
        
        avg_purchase_amount = st.number_input(
            "Average Purchase Amount (Rs. )",
            min_value=0.0,
            max_value=10000.0,
            value=50.0,
            step=5.0,
            help="Average amount per purchase"
        )
        
        min_purchase_amount = st.number_input(
            "Minimum Purchase Amount (Rs. )",
            min_value=0.0,
            max_value=1000.0,
            value=10.0,
            step=1.0
        )
        
        max_purchase_amount = st.number_input(
            "Maximum Purchase Amount (Rs. )",
            min_value=0.0,
            max_value=10000.0,
            value=100.0,
            step=10.0
        )
        
        total_purchases = st.number_input(
            "Total Number of Purchases",
            min_value=1,
            max_value=10000,
            value=15,
            help="Total items/products purchased"
        )
    
    with input_col2:
        st.markdown("#### 📅 Customer Timeline & Engagement")
        
        recency = st.number_input(
            "Recency (Days Since Last Purchase)",
            min_value=0,
            max_value=1000,
            value=30,
            help="Number of days since last purchase"
        )
        
        tenure_days = st.number_input(
            "Tenure (Days as Customer)",
            min_value=1,
            max_value=3650,
            value=180,
            help="Number of days since first purchase"
        )
        
        std_purchase_amount = st.number_input(
            "Purchase Amount Std Deviation (Rs. )",
            min_value=0.0,
            max_value=1000.0,
            value=15.0,
            step=1.0,
            help="Standard deviation of purchase amounts"
        )
        
        purchase_frequency = total_purchases / max(tenure_days, 1)
        st.metric("Calculated Purchase Frequency", f"{purchase_frequency:.4f} purchases/day")
        
        clv_estimate = (total_revenue / max(tenure_days, 1)) * 365
        st.metric("Simple CLV Estimate", f"Rs. {clv_estimate:.2f}")
    
    st.markdown("---")
    
    # Categorical inputs
    cat_col1, cat_col2, cat_col3, cat_col4 = st.columns(4)
    
    with cat_col1:
        product_category = st.selectbox(
            "Primary Product Category",
            ["Electronics", "Clothing", "Home & Garden", "Sports", "Books"]
        )
    
    with cat_col2:
        payment_method = st.selectbox(
            "Primary Payment Method",
            ["Credit Card", "Debit Card", "UPI", "Cash on Delivery"]
        )
    
    with cat_col3:
        customer_segment = st.selectbox(
            "Customer Segment",
            ["Loyal", "Returning", "New"]
        )
    
    with cat_col4:
        region = st.selectbox(
            "Region",
            ["North", "South", "East", "West"]
        )
    
    st.markdown("---")
    
    # Predict button
    if st.button("🚀 Generate Predictions", type="primary", use_container_width=True):
        
        # Prepare input data for churn prediction
        input_data = {
            'total_invoices': total_invoices,
            'total_revenue': total_revenue,
            'avg_purchase_amount': avg_purchase_amount,
            'std_purchase_amount': std_purchase_amount,
            'min_purchase_amount': min_purchase_amount,
            'max_purchase_amount': max_purchase_amount,
            'total_purchases': total_purchases,
            'recency': recency,
            'tenure_days': tenure_days,
            'purchase_frequency': purchase_frequency
        }
        
        # Create dataframe
        input_df = pd.DataFrame([input_data])
        
        # Add categorical variables (one-hot encoding)
        # Get all possible categorical values from feature_names
        categorical_features = [f for f in feature_names if any(
            cat in f for cat in ['primary_product_category', 'primary_payment_method', 
                                  'customer_segment', 'region']
        )]
        
        # Initialize all categorical features to 0
        for feature in categorical_features:
            input_df[feature] = 0
        
        # Set the selected categories to 1
        if f'primary_product_category_{product_category}' in feature_names:
            input_df[f'primary_product_category_{product_category}'] = 1
        if f'primary_payment_method_{payment_method}' in feature_names:
            input_df[f'primary_payment_method_{payment_method}'] = 1
        if f'customer_segment_{customer_segment}' in feature_names:
            input_df[f'customer_segment_{customer_segment}'] = 1
        if f'region_{region}' in feature_names:
            input_df[f'region_{region}'] = 1
        
        # Reorder columns to match feature_names
        #input_df = input_df[feature_names]
        
        # Scale the input
        input_scaled = churn_scaler.transform(input_df)
        
        # CHURN PREDICTION
        churn_prediction = churn_model.predict(input_scaled)[0]
        churn_probability = churn_model.predict_proba(input_scaled)[0] if hasattr(churn_model, 'predict_proba') else None
        
        # CLV PREDICTION using Gamma-Gamma model
        # Calculate frequency (number of repeat purchases)
        frequency = max(total_purchases - 1, 0)  # -1 because first purchase doesn't count
        monetary_value = avg_purchase_amount
        
        # Predict expected average order value using Gamma-Gamma
        if frequency > 0:
            expected_avg_order_value = gg_model.conditional_expected_average_profit(
                frequency=frequency,
                monetary_value=monetary_value
            )
            clv_proxy = expected_avg_order_value * frequency
        else:
            expected_avg_order_value = monetary_value
            clv_proxy = monetary_value
        
        # Display Results
        st.markdown("---")
        st.subheader("🎯 Prediction Results")
        
        result_col1, result_col2 = st.columns(2)
        
        with result_col1:
            st.markdown("### 📉 Churn Analysis")
            
            if churn_prediction == 1:
                st.error("⚠️ **HIGH RISK**: Customer likely to churn")
                risk_level = "High"
                risk_color = "red"
            else:
                st.success("✅ **LOW RISK**: Customer likely to stay")
                risk_level = "Low"
                risk_color = "green"
            
            if churn_probability is not None:
                churn_prob_pct = churn_probability[1] * 100
                st.metric("Churn Probability", f"{churn_prob_pct:.2f}%")
                
                # Progress bar for churn probability
                fig_churn = go.Figure(go.Indicator(
                    mode="gauge+number",
                    value=churn_prob_pct,
                    title={'text': "Churn Risk Level"},
                    gauge={
                        'axis': {'range': [None, 100]},
                        'bar': {'color': risk_color},
                        'steps': [
                            {'range': [0, 30], 'color': "lightgreen"},
                            {'range': [30, 70], 'color': "yellow"},
                            {'range': [70, 100], 'color': "lightcoral"}
                        ],
                        'threshold': {
                            'line': {'color': "red", 'width': 4},
                            'thickness': 0.75,
                            'value': 70
                        }
                    }
                ))
                fig_churn.update_layout(height=300)
                st.plotly_chart(fig_churn, use_container_width=True)
            
            # Recommendations
            st.markdown("#### 💡 Recommendations")
            if churn_prediction == 1:
                st.markdown("""
                - 🎁 Offer loyalty rewards or discounts
                - 📧 Send personalized re-engagement emails
                - 📞 Reach out with customer support
                - 🎯 Target with special promotions
                """)
            else:
                st.markdown("""
                - 🌟 Maintain current engagement level
                - 📈 Encourage upselling opportunities
                - 💬 Request feedback for improvement
                - 🔔 Keep informed about new products
                """)
        
        with result_col2:
            st.markdown("### 💰 Customer Lifetime Value")
            
            st.metric("Predicted CLV (Gamma-Gamma)", f"Rs. {clv_proxy:.2f}")
            st.metric("Expected Avg Order Value", f"Rs. {expected_avg_order_value:.2f}")
            st.metric("Frequency (Repeat Purchases)", frequency)
            
            # CLV Breakdown
            fig_clv = go.Figure(go.Indicator(
                mode="number+delta",
                value=clv_proxy,
                title={'text': "Customer Lifetime Value (Rs.)"},
                delta={'reference': total_revenue, 'relative': False},
                domain={'x': [0, 1], 'y': [0, 1]}
            ))
            fig_clv.update_layout(height=250)
            st.plotly_chart(fig_clv, use_container_width=True)
            
            # Value breakdown
            st.markdown("#### 📊 Value Breakdown")
            breakdown_data = pd.DataFrame({
                'Metric': ['Total Revenue', 'Expected Order Value', 'CLV Proxy'],
                'Value': [total_revenue, expected_avg_order_value, clv_proxy]
            })
            fig_breakdown = px.bar(
                breakdown_data,
                x='Metric',
                y='Value',
                color='Metric',
                title="Value Comparison"
            )
            st.plotly_chart(fig_breakdown, use_container_width=True)
        
        # Customer Insights
        st.markdown("---")
        st.subheader("🔍 Customer Insights")
        
        insight_col1, insight_col2, insight_col3, insight_col4 = st.columns(4)
        
        with insight_col1:
            st.metric("Total Purchases", total_purchases)
        
        with insight_col2:
            st.metric("Avg Purchase", f"Rs. {avg_purchase_amount:.2f}")
        
        with insight_col3:
            st.metric("Days Since Last Purchase", recency)
        
        with insight_col4:
            st.metric("Customer Tenure (Days)", tenure_days)

# ============================
# TAB 2: DATA ANALYSIS
# ============================
with tab2:
    st.header("📊 Exploratory Data Analysis")
    
    customer_data = cld()
    
    if customer_data is not None:
        st.markdown("### Dataset Overview")
        
        overview_col1, overview_col2, overview_col3, overview_col4 = st.columns(4)
        
        with overview_col1:
            st.metric("Total Customers", len(customer_data))
        
        with overview_col2:
            st.write(customer_data.columns)
            churn_count = customer_data['churn'].sum()
            st.metric("Churned Customers", churn_count)
        
        with overview_col3:
            churn_rate = (churn_count / len(customer_data)) * 100
            st.metric("Churn Rate", f"{churn_rate:.2f}%")
        
        with overview_col4:
            avg_clv = customer_data['clv_estimate'].mean()
            st.metric("Avg CLV Estimate", f"Rs. {avg_clv:.2f}")
        
        st.markdown("---")
        
        # Visualization options
        viz_col1, viz_col2 = st.columns(2)
        
        with viz_col1:
            st.markdown("#### Churn Distribution")
            churn_dist = customer_data['churn'].value_counts()
            fig_churn_dist = px.pie(
                values=churn_dist.values,
                names=['Not Churned', 'Churned'],
                title="Churn Distribution",
                color_discrete_sequence=['#00CC96', '#EF553B']
            )
            st.plotly_chart(fig_churn_dist, use_container_width=True)
        
        with viz_col2:
            st.markdown("#### CLV Distribution")
            fig_clv_dist = px.histogram(
                customer_data,
                x='clv_estimate',
                nbins=30,
                title="Customer Lifetime Value Distribution",
                labels={'clv_estimate': 'CLV Estimate (Rs.)'}
            )
            st.plotly_chart(fig_clv_dist, use_container_width=True)
        
        st.markdown("---")
        
        viz_col3, viz_col4 = st.columns(2)
        
        with viz_col3:
            st.markdown("#### Revenue vs Recency")
            fig_scatter = px.scatter(
                customer_data,
                x='recency',
                y='total_revenue',
                color='churn',
                title="Revenue vs Recency (colored by Churn)",
                labels={'recency': 'Days Since Last Purchase', 'total_revenue': 'Total Revenue (Rs.)'},
                color_discrete_map={0: '#00CC96', 1: '#EF553B'}
            )
            st.plotly_chart(fig_scatter, use_container_width=True)
        
        with viz_col4:
            st.markdown("#### Purchase Frequency Distribution")
            fig_freq = px.histogram(
                customer_data,
                x='purchase_frequency',
                nbins=30,
                title="Purchase Frequency Distribution",
                labels={'purchase_frequency': 'Purchase Frequency (purchases/day)'}
            )
            st.plotly_chart(fig_freq, use_container_width=True)
        
        st.markdown("---")
        st.markdown("### 📋 Sample Customer Data")
        st.dataframe(customer_data.head(20), use_container_width=True)

        st.markdown("---")
        #write a code to visualize a bar chart and segment customers based on payment methods
        st.markdown("#### Payment Method Distribution")
        payment_method_counts = customer_data['primary_payment_method_x'].value_counts()
        fig_payment = px.bar(
            x=payment_method_counts.index,
            y=payment_method_counts.values,
            title="Customer Distribution by Payment Method",
            labels={'x': 'Payment Method', 'y': 'Number of Customers'}
        )
        st.plotly_chart(fig_payment, use_container_width=True)

        st.markdown("---")
        #
        
    else:
        st.warning("Customer data not available for analysis.")

# ============================
# TAB 3: ABOUT
# ============================
with tab3:
    st.header("ℹ️ About This Customer Data Platform")
    
    st.markdown("""
    ### 🎯 Platform Overview
    
    This Customer Data Platform (CDP) is designed to help businesses understand and predict customer behavior through advanced analytics and machine learning.
    
    ### 🔧 Key Features
    
    #### 1. **Churn Prediction**
    - Predicts whether a customer is likely to stop purchasing
    - Uses machine learning models (Logistic Regression, Random Forest, SVC)
    - Provides actionable recommendations for customer retention
    
    #### 2. **Customer Lifetime Value (CLV) Prediction**
    - Estimates the total value a customer will bring over their lifetime
    - Uses **Gamma-Gamma Model** from the lifetimes library
    - Helps prioritize high-value customers for marketing efforts
    
    #### 3. **Data Analysis Dashboard**
    - Interactive visualizations of customer behavior
    - Churn rate and CLV distribution analysis
    - Customer segmentation insights
    
    ### 📊 Models Used
    
    **Churn Prediction Models:**
    - Logistic Regression
    - Random Forest Classifier
    - Support Vector Classifier (SVC)
    
    **CLV Prediction Model:**
    - Gamma-Gamma Fitter (probabilistic model for monetary value prediction)
    
    ### 🚀 Technology Stack
    
    - **Frontend**: Streamlit
    - **ML Libraries**: scikit-learn, lifetimes
    - **Visualization**: Plotly
    - **Data Processing**: Pandas, NumPy
    
    ### 📖 How to Use
    
    1. **Navigate to Predictions Tab**: Input customer data and get instant predictions
    2. **View Data Analysis Tab**: Explore patterns in your customer base
    3. **Export Results**: Use predictions to inform marketing and retention strategies
    
    ### 💡 Business Applications
    
    - **Marketing**: Target high-value customers with personalized campaigns
    - **Retention**: Identify at-risk customers and implement retention strategies
    - **Resource Allocation**: Prioritize customer service efforts based on CLV
    - **Revenue Forecasting**: Predict future revenue from customer base
    
    ### 📝 Notes
    
    - All predictions are based on historical customer behavior patterns
    - Regular model retraining is recommended for optimal performance
    - This is a prototype version; production deployment requires additional security and scalability considerations
    
    ---
    
    **Version**: 1.0  
    **Last Updated**: February 2026
    
    For questions or support, please contact Devahuti Gogoi (devahuti.gogoi@u.nus.edu)..
    """)

# Sidebar
with st.sidebar:
    st.image("/Users/apple/Desktop/MARKETING PROJ/image.png", width=150)
    st.markdown("## 🎛️ Dashboard Controls")
    st.markdown("---")
    
    st.markdown("### 📌 Quick Stats")
    customer_data = load_customer_data()
    if customer_data is not None:
        st.metric("Total Customers", len(customer_data))
        st.metric("Active Models", "2")
        st.metric("Features Used", len(feature_names))
    
    
    st.markdown("---")
    st.markdown("### ℹ️ Model Info")
    st.info(f"**Churn Model**: {type(churn_model).__name__}")
    st.info("**CLV Model**: Gamma-Gamma Fitter")
    
    st.markdown("---")
    st.markdown("Made with ❤️ using Streamlit + .py + .ipynb by Devahuti")
